yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
# импорт include позволит использовать адреса, включенные в приложения
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    # Django проверяет url-адреса сверху вниз,
    # нам нужно, чтобы Django сначала проверял адреса в приложении users
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        related_name='comment',
        verbose_name='Пост',
        on_delete=models.CASCADE,
    )
    author = models.ForeignKey(
        User,
        related_name='comment',
        verbose_name='Автор',
        on_delete=models.CASCADE,
    )
    text = models.TextField(
        'Комментарий',
        help_text='Введите комеентарий',
    )
    created = models.DateTimeField(
        auto_now_add=True
    )


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['author', 'user'],
                name='unique_follow'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text', 'image')
        labels = {"text": "Текст поста", "group": "Группа"}
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Комментарий', }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

MAX_NUM_OF_POSTS = 10  # Максимальное количество постов на странице


def get_page_context(post_list, request):
    paginator = Paginator(post_list, MAX_NUM_OF_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return {
        'paginator': paginator,
        'page_number': page_number,
        'page_obj': page_obj,
    }


def index(request):
    """Выводит шаблон главной страницы"""
    context = get_page_context(Post.objects.all(), request)
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Выводит шаблон с группами постов"""
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    context = {
        'group': group,
        'post_list': post_list,
    }
    context.update(get_page_context(group.posts.all(), request))
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Выводит шаблон профайла пользователя"""
    template_name = 'posts/profile.html'
    user = User.objects.get(username=username)
    posts = user.posts.select_related("group")
    post_count = posts.count()
    following = request.user.is_authenticated
    if following:
        following = user.following.filter(user=request.user).exists()
    context = {
        'post_count': post_count,
        'author': user,
        'following': following,
    }
    context.update(get_page_context(user.posts.all(), request))
    return render(request, template_name, context)


def post_detail(request, post_id):
    template_name = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    context = {
        'post': post,
        'form': CommentForm(),
        'comments': post.comment.all(),
    }
    return render(request, template_name, context)


@login_required
def post_create(request):
    post = Post(author=request.user)
    form = PostForm(request.POST or None, instance=post)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("posts:profile", request.user.username)
    context = {
        "form": form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        instance=post,
        files=request.FILES or None,
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    # информация о текущем пользователе доступна в переменной request.user
    # ...
    post = Post.objects.filter(
        author__following__user=request.user)
    context = {
        'post': post,
    }
    context.update(get_page_context(post, request))
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    # Подписаться на автора
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect(
            'posts:profile',
            username=username
        )
    follower = Follow.objects.filter(
        user=request.user,
        author=author
    ).exists()
    if follower is True:
        return redirect(
            'posts:profile',
            username=username
        )
    Follow.objects.create(user=request.user, author=author)
    return redirect(
        'posts:profile',
        username=username
    )


@login_required
def profile_unfollow(request, username):
    # Дизлайк, отписка
    author = get_object_or_404(User, username=username)
    if author == request.user:
        return redirect(
            'posts:profile',
            username=username
        )
    following = get_object_or_404(Follow, user=request.user, author=author)
    following.delete()
    return redirect(
        'posts:profile',
        username=username
    )

yatube/templates/posts/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %} 

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block  title %}{% if not is_edit %}<title>Новый пост</title>{% else %}<title>Редактировать пост</title>{% endif %}{% endblock %}
{% load user_filters %}
  {% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                {% if not is_edit %}Добавить запись{% else %}Редактировать запись{% endif %}            
              </div>
              <div class="card-body">
                <form method="post" 
                  {% if is_edit %} 
                      action="{% url 'posts:post_edit' post.id %}" 
                  {% else %}
                      action="{% url 'posts:post_create' %}" 
                  {% endif %} enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    {{ form.text|addclass:'form-control' }}                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                 
                    </label>
                    {{ form.group|addclass:'form-control' }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                    {{ form.image|addclass:'form-control' }}
                    <small id="id_text-help" class="form-text text-muted">
                      Картинка поста
                    </small>  
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if not is_edit %}Добавить{% else %}Сохранить{% endif %}               
                    </button> 
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  {% endblock content %}  

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}
{% block title %}
  <title> Мои подписки </title>
{% endblock %}
  <main> 
    {% block content %}
    {% include 'posts/switcher.html'%}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>Мои пописки</h1>
        <article>
          {% cache 20 index_page %}
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>      
              {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
              {% endthumbnail %}
            <p>{{ post.text }}</p>
              {% if post.group %}   
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 
            {% endcache %} 
          {% include 'posts/includes/paginator.html' %}
        <article>
      </div> 
    {% endblock %}  
  </main>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
{% for post in posts %}
  <title> Записи сообщества {{ post.group }} </title>
{% endfor %}
{% endblock %}
  <main> 
    {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        <h1> {{group.title}} </h1>
          <p>
            {{group.description}}
          </p>
            <article>
              {% for post in page_obj %}
              <ul>
                <li>
                  Автор: {{ post.author.get_full_name }}
                </li>
                <li>
                  Дата публикации: {{ post.pub_date|date:"d E Y" }}
                </li>
              </ul>      
                {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                  <img class="card-img my-2" src="{{ im.url }}">
                {% endthumbnail %}
                <p>{{ post.text }}</p>
            </article>
            <!-- под последним постом нет линии -->
            {% if not forloop.last %}<hr>{% endif %}
            {% endfor %}

            {% include 'posts/includes/paginator.html' %}
      </div>
    {% endblock %}  

   

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}
  <title> Последние обновления на сайте </title>
{% endblock %}
  <main> 
    {% block content %}
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">     
        <h1>Последние обновления на сайте</h1>
        <article>
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>      
            <p>{{ post.text }}</p>
              {% if post.group %}   
                <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
              {% endif %} 
            {% if not forloop.last %}<hr>{% endif %}
          {% endfor %} 

          {% include 'posts/includes/paginator.html' %}
          
        <article>
      </div> 
    {% endblock %}  
  </main>

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    <title>{{ post.text|truncatechars:30 }}</title>
{% endblock %}
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            {% if post.group %}   
            <li class="list-group-item">
              Группа: {{post.group.title}}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{post.author.get_full_name}}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора: {{ post.author.posts.count }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            {{ post.text|linebreaksbr }}
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
          </p>
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}" role="button">Редактировать</a>
          {% include 'posts/comment.html'%}
        </article>
      </div> 
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
    <title>Профайл пользователя {{post.author.get_full_name}}</title>
{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">        
        <h1>Все посты пользователя {{post.author.get_full_name}} </h1>
        <h3>Всего постов: {{author.posts.count}} </h3>  
        {% if following %}
          <a
            class="btn btn-lg btn-light"
            href="{% url 'posts:profile_unfollow' author.username %}" role="button"
          >
            Отписаться
          </a>
        {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' author.username %}" role="button"
            >
              Подписаться
            </a>
        {% endif %} 
        {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{post.author.get_full_name}}
              </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          <p>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            {{ post.text|safe|linebreaksbr }}
          </p>
          {% if post.group %}   
            <a href="{% url 'posts:group_list' post.group.slug %}"> группа: {{post.group.title}} </a>
          {% endif %} 
            <br>
            <a href="{% url 'posts:post_detail' post.id %}"> подробная информация </a>
          </article> 
        <!-- Остальные посты. после последнего нет черты -->
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}  
        <!-- Здесь подключён паджинатор -->  
        {% include 'posts/includes/paginator.html' %}
      </div>
      
{% endblock %}

</main>

yatube/templates/posts/switcher.html
{% if user.is_authenticated %}
  <div class="row my-3">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a 
          class="nav-link {% if index %}active{% endif %}"
          href="{% url 'posts:index' %}"
        >
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a 
           class="nav-link {% if follow %}active{% endif %}"
           href="{% url 'posts:follow_index' %}"
        >
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}